### ISSUE TITLE
posix_fallocate is Linux-specific

### ISSUE THREAD

**Issue by bscottm** [osicat/osicat#10]
Latest version bails on Mac OSX. Suggest the following one line change in front of the posix_fallocate wrapper declaration:

Line 151, posix/wrappers.lisp, was:

    #-windows
    (defwrapper "posix_fallocate" ("int" (errno-wrapper :int

Should be:

    #-(or windows darwin macosx)
    (defwrapper "posix_fallocate" ("int" (errno-wrapper :int

For consistency, since there aren't other references to `macosx` in `*features*`, it could just be:

    #-(or windows darwin)
    (defwrapper "posix_fallocate" ("int" (errno-wrapper :int

(Really, you want me to clone and submit a patch on a one-line fix?)

**Comment by luismbo** [comment]
You can click edit right from the GitHub interface! Try it! :)

**Comment by luismbo** [comment]
Shouldn't it be #+linux then?

**Comment by luismbo** [comment]
Maybe use `#+linux`?

**Comment by jackcarrozzo** [comment]
+1, this works for me.

**Comment by lispnik** [comment]
Added #11 to make call this #+linux

**Comment by luismbo** [comment]
Thanks @lispnik. Merged.

**Comment by xinranmsn** [comment]
`#+linux` fails on OS X.  `#-(or windows darwin)` works.
