### ISSUE TITLE
Dead code warning.

### ISSUE THREAD

**Issue by Ferada** [osicat/osicat#13]
When compiling the package at the moment there's a dead code warning in `%open-temporary-file/no-fd-streams` for the `counter`, which seems reasonable, since the `(return stream)` will always be invoked. The original intent was "try a hundred times before failing"(?), so this might have been introduced while rewriting?

I don't exactly know in which way to fix this; the retry already seems a bit suspect.

**Comment by luismbo** [comment]
@Ferada does ae5bfa6 look right to you?

**Comment by Ferada** [comment]
@luismbo yes, I think so.

**Comment by luismbo** [comment]
Oops, ae5bfa6 failed the test suite miserably. How about 83de82e?

**Comment by luismbo** [comment]
That seems a little bit better, but I have to admit I haven't tested it thoroughly. :-/

**Comment by Ferada** [comment]
Indentation looks like the body of the `unwind-protect-case` needs two spaces more each, otherwise test cases for both with and without `:osicat-fd-streams` run through successfully for me.
