### ISSUE TITLE
Error during installation: OPERATION instances must only be created through MAKE-OPERATION.

### ISSUE THREAD

**Issue by yoeljacobsen** [osicat/osicat#18]
Tested on latest SBCL and CCL.

ASDF version is 3.1.7.40

**Comment by pashosh** [comment]
also here.
can't install slime in both archlinux and gentoo.
sbcl is 1.3.15
asdf is 3.2.0

here is the full error:
* (ql:quickload "quicklisp-slime-helper")
To load "quicklisp-slime-helper":
  Load 1 ASDF system:
    quicklisp-slime-helper
; Loading "quicklisp-slime-helper"

debugger invoked on a ASDF/FIND-SYSTEM:FORMATTED-SYSTEM-DEFINITION-ERROR in thread
#<THREAD "main thread" RUNNING {100215E473}>:
  OPERATION instances must only be created through MAKE-OPERATION.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY                        ] Retry
                                     compiling #<NO-LOAD-FILE "swank" "contrib" "swank-c-p-c">.
  1: [ACCEPT                       ] Continue, treating
                                     compiling #<NO-LOAD-FILE "swank" "contrib" "swank-c-p-c">
                                     as having been successful.
  2:                                 Retry ASDF operation.
  3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  4: [ABORT                        ] Give up on "quicklisp-slime-helper"
  5:                                 Exit debugger, returning to top level.

(ASDF/FIND-SYSTEM:SYSDEF-ERROR "OPERATION instances must only be created through MAKE-OPERATION.")
   error finding frame source: Bogus form-number: the source file has probably
                               changed too much to cope with.
   source: NIL

**Comment by luismbo** [comment]
@pashosh how is this related to Osicat?

@yoeljacobsen do you still have this issue?

**Comment by pashosh** [comment]
@luismbo yes i'm sorry.
i just realize it isn't belong to here :-)

**Comment by yoeljacobsen** [comment]
Yes. Failed again on SBCL 1.3.15 and  CCL 1.11.

בתאריך יום א׳, 19 במרץ 2017, 19:27, מאת pashosh ‏<notifications@github.com>:

**Comment by luismbo** [comment]
Can't reproduce with SBCL 14.0 and ASDF 3.3.0 or 3.1.5, sorry.
