### ISSUE TITLE
Build failure with musl-libc

### ISSUE THREAD

**Issue by lipidity** [osicat/osicat#19]
Seems to be an issue with the musl libc headers. [Here's the log](https://github.com/osicat/osicat/files/672325/log.txt) showing the error: `'struct sigevent' has no member named '_sigev_un'; did you mean 'sigev_value'?`

The relevant definition that I could find on my system in /usr/include/asm-generic/siginfo.h reads:

	typedef struct sigevent {
	        sigval_t sigev_value;
	        int sigev_signo;
	        int sigev_notify;
	        union {
	                int _pad[SIGEV_PAD_SIZE];
	                 int _tid;
	
	                struct {
	                        void (*_function)(sigval_t);
	                        void *_attribute;       /* really pthread_attr_t */
	                } _sigev_thread;
	        } _sigev_un;
	} sigevent_t;

Any ideas?

**Comment by luismbo** [comment]
Can we detect the presence of musl somehow? Perhaps we can use a `(c "#ifdef ...")` around this particular definition. (Things that use it later on would need to be adapted as well.)

**Comment by Ferada** [comment]
Can probably test for presence of `SIGEV_THREAD_ID`, that's not defined with musl and possibly less hacky than testing for glibc explicitly.

**Comment by mister-walter** [comment]
Just ran into this when another program used Quicklisp to build osicat inside of an Alpine Linux Docker image (Alpine uses musl).

I'm willing to take a shot at implementing @Ferada 's suggestion if that approach seems reasonable.

**Comment by luismbo** [comment]
@Ferada's suggestion sounds good, yes. Don't forget to adapt [`timer-create`](https://github.com/osicat/osicat/blob/9cc248c09325c55ae05b3933b9292e8a14e69718/posix/unix.lisp#L409) accordingly.

**Comment by gjabell** [comment]
Has there been any progress on this issue? I would like to try [Next](https://github.com/atlas-engineer/next) on Alpine but it now depends on Osicat which still fails with the same error as above.
