### ISSUE TITLE
stat fails on broken symlinks

### ISSUE THREAD

**Issue by Ambrevar** [osicat/osicat#40]
Recipe:

```sh
$ ln -s non-existent-file broken-symlink 
```

```lisp
> (osicat-posix:stat "broken-symlink")

#<ENOENT "[No syscall name]" 2 :ENOENT "No such file or directory">
   [Condition of type OSICAT-POSIX:ENOENT]
```

I believe Osicat can be fixed to retrieve the links information nonetheless, like `ls` does.

**Comment by Ambrevar** [comment]
Might be related to #15.

**Comment by luismbo** [comment]
If `stat(2)` is yielding ENOENT then there's nothing else to do in the osicat-posix layer. Higher-level layers should do something else, agreed, which is what #15 is about. Do you feel like taking a stab at #15?

**Comment by Ambrevar** [comment]
Any idea how to go by it?
I don't know how `ls`, etc. retrieve the metadata from such files.

**Comment by luismbo** [comment]
It probably uses `lstat` rather than `stat`, or falls back to `lstat` if `stat` yields ENOENT.

**Comment by Ambrevar** [comment]
Right, this seems to do the trick.
Can't lstat be added to Osicat then?
If not, where else?

**Comment by luismbo** [comment]
Osicat does have lstat, what do you mean?

**Comment by Ambrevar** [comment]
Oooooh, I had missed it because it's private! :p

OK, can we make it public then? :)

**Comment by luismbo** [comment]
Oh, yes of course, that seems like a bug.

**Comment by Ambrevar** [comment]
Should I open an issue about it or is it trivial enough for you to just export it?

**Comment by luismbo** [comment]
If you can open a pull request, that'd be great. Thanks for catching this.

**Comment by Ambrevar** [comment]
My bad, `lstat` is already public O.o
I must have been very tired when I checked.
Well... All good then!
