### ISSUE TITLE
I can't install osicat

### ISSUE THREAD

**Issue by Centrix14** [osicat/osicat#42]
Hello, I'm trying to install osicat using quicklisp, but nothing works. When installing in CCL, I get this error:
```
> Error: Unable to load foreign library (LIBOSICAT).
>          Error opening shared library libosicat.dll : Не найден указанный модуль. .
> While executing: CFFI::FL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

Then I tried to install osicat in CLISP, and here I was waiting for the same thing:
```
... A lot of linker errors ...

*** - Subprocess with command
("gcc" "-o" "C:\\Users\\User\\AppData\\Local\\cache\\common-lisp\\clisp-2.49-win-x86\\D\\msys2\\home\\User\\quicklisp\\dists\\quicklisp\\software\\osicat-20200925-git\\posix\\basic-unixint__grovel-tmpCTJRV7CV.exe" "-m32" "-Wl,--export-dynamic" "C:\\Users\\User\\AppData\\Local\\cache\\common-lisp\\clisp-2.49-win-x86\\D\\msys2\\home\\User\\quicklisp\\dists\\quicklisp\\software\\osicat-20200925-git\\posix\\basic-unixint__grovel.obj")exited with error code 1
```

After this failure, I started installing osicat in SBCL, and nothing good came out here either:
```
debugger invoked on a CFFI:LOAD-FOREIGN-LIBRARY-ERROR in thread
#<THREAD "main thread" RUNNING {10010B0523}>:
Unable to load foreign library (LIBOSICAT).
Error opening shared object "libosicat.dll":
```

No matter what I tried to do, I couldn't install osicat.

System: Windows 8.1 (msys2)
CCL: `Version 1.12 (v1.12) WindowsX8664`
CLISP:  `GNU CLISP 2.49 (2010-07-07)`
SBCL: `SBCL 2.0.0`

I will be glad of any help. Thanks!

**Comment by luismbo** [comment]
You need to ensure gcc is in the PATH. An easy way to do that would be to
launch your Lisp within the msys console. We should fix this on Windows to
not require msys somehow since Windows has a stable ABI and shouldn't
really need this sort of groveling.

**Comment by Centrix14** [comment]
@luismbo Unfortunately, this did not help me. Here's what CCL gave out:
```
To load "osicat":
  Load 1 ASDF system:
    osicat
; Loading "osicat"
; gcc -o C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel-tmpA5WIWL59.obj -c -m64 -IC:/Users/User/quicklisp/dists/quicklisp/software/cffi_0.23.0/ C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel.c
; gcc -o C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel-tmp97W8N8F7.exe -m64 -Wl,--export-dynamic C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel.obj
D:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: --export-dynamic is not supported for PE+ targets, did you mean --export-all-symbols?
; C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel.exe C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel.grovel-tmp.lisp
.................; gcc -o C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/wrappers__wrapper-tmpW2BJXM5B.obj -c -m64 -IC:/Users/User/quicklisp/dists/quicklisp/software/cffi_0.23.0/ C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/wrappers__wrapper.c
; gcc -o C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/libosicat.dll -shared -m64 C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/wrappers__wrapper.obj
.
> Error: Unable to load foreign library (LIBOSICAT).
>          Error opening shared library libosicat.dll : Не найден указанный модуль. .
> While executing: CFFI::FL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

**Comment by luismbo** [comment]
Is GCC installed? If not, you need to install it. (`pacman -S --needed mingw-w64-x86_64-gcc` or something like that.) If it is, installed, perhaps Quicklisp is omitting the error message? Try loading osicat using `(asdf:load-system :osicat)` or run some of those gcc commands manually to see if that yields any hint.

**Comment by Centrix14** [comment]
@luismbo 
> Is GCC installed?

GCC has been installed all this time.
I also tried the commands that quicklisp generates, but only one failed:
```
gcc -o C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel-tmpWAXRB1K1.exe -m64 -Wl,--export-dynamic C:/Users/User/AppData/Local/cache/common-lisp/ccl-1.12-f98-win-x64/C/Users/User/quicklisp/dists/quicklisp/software/osicat-20210228-git/posix/basic-unixint__grovel.obj
D:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: warning: --export-dynamic is not supported for PE+ targets, did you mean --export-all-symbols?
```

When I try to load osicat via `(asdf:load-system :osicat)`, I get the same error as when installing using quicklisp:
```
> Error: Unable to load foreign library (LIBOSICAT).
>          Error opening shared library libosicat.dll : The specified module was not found
> While executing: CFFI::FL-ERROR, in process listener(1).
> Type :POP to abort, :R for a list of available restarts.
> Type :? for other options.
```

**Comment by luismbo** [comment]
Try using the suggested option. (Or no option at all. Not sure why we're passing that option when this isn't a DLL.)

**Comment by Centrix14** [comment]
After investigating the quicklisp directory a little, I found that libosicat exists and is installed, the only question is in what place it should be located? (I tried to find out with the help of restarts, but nothing happened)

**Comment by Centrix14** [comment]
I solved this problem: all I had to do was move `libosicat` to `/usr/bin`. Thank you for your cooperation!

**Comment by luismbo** [comment]
@Centrix14 if you have time to investigate this a bit further, it'd be nice to see why we're failing to load libosicat.dll from its original location. Perhaps you can load CFFI beforehand, `(trace cffi:load-foreign-library)` to see where it's looking for the DLL. (I believe it's being loaded here: https://github.com/cffi/cffi/blob/677cabae64b181330a3bbbda9c11891a2a8edcdc/toolchain/c-toolchain.lisp#L384)

Also, can you run `ldd libosicat.dll` to see if perhaps it ended up depending on other DLLs that aren't in the path?

**Comment by philomelus** [comment]
> [@philomelus](https://github.com/philomelus) if you turn Quicklisp's verbosity on or use ASDF directly you should be able to see the cc command being invoked to compile the DLL.

Thanks, that gave me what I needed.  Now I just have to figure out how to fix it.  It appended (er, prepended) the Windows cache location to the MSYS2/UCRT64 location.  It wrote it to

`"C:\Users\<username>\AppData\Local\cache\common-lisp\sbcl-2.5.6-win-x64\E\Data\home\quicklisp\dists\quicklisp\software\osicat-20250622-git\posix\libosicat.dll"`

It should have just used:

`"/E/Data/home/quicklisp/dists/quicklisp/software/osicat-20250622-git/posix/libosicat.dll"`
or 
`"~/quicklisp/dists/quicklisp/software/osicat-20250622-git/posix/libosicat.dll"`

Where ~ is "/e/Data/home".

Somewhere there is code that detects it Windows, but doesn't recognize that its MSYS2.  I'll spend some time looking into it (for the experience more than the solve;  I'm thinking its a quicklisp issue not osicat's).

Thanks for the help!
