### ISSUE TITLE
futime causing a linker error

### ISSUE THREAD

**Issue by Slids** [osicat/osicat#58]
utime is an always supported syscall, but futime is not.
It's causing a linker error for me:

ld: error: undefined symbol: futime
>>> referenced by SYS:SRC;CODE;SAVE.LISP
>>>               blaze-out/k8-opt/bin/third_party/lisp/osicat/_objs/~osicat-library-test/~osicat-library-test.o:(%futime)
>>> referenced by SYS:SRC;CODE;SAVE.LISP
>>>               blaze-out/k8-opt/bin/third_party/lisp/osicat/_objs/~osicat-library-test/~osicat-library-test.o:(FUTIME)
>>> referenced by SYS:SRC;CODE;SAVE.LISP
>>>               blaze-out/k8-opt/bin/third_party/lisp/osicat/_objs/~osicat-library-test/~osicat-library-test.o:
>>> did you mean: utime

Can we remove futime and just say use utime?

**Comment by daewok** [comment]
Huh. Sorry about that. `futime` is present in Windows and I forgot to check the other OSes, apparently foolishly assuming that Windows was the lowest common denominator. I'll have a fix in the next day or so.
