### ISSUE TITLE
Memory leak opening and closing file with osicat-posix:open

### ISSUE THREAD

**Issue by kayhman** [osicat/osicat#8]
Hi,

I experience memory leaks when opening and closing file with osicat-posix:open, using sbcl 1.2.11

When I run the code below, my sbcl process memory use augments by some hundred MB:

(defun testmemleak ()
(dotimes (i 10000000)
(let ((fd (osicat-posix:open "/tmp/memleak" (logior osicat-posix:o-rdwr))))
(osicat-posix:close fd))))

If I run the same code, but using sb-posix instead of osicat-posix, I don't have the issue.

Regards

**Comment by luismbo** [comment]
Ouch, the foreign types defined via `define-designator` were leaking badly. Should be fixed now. Thanks!
